### PR TITLE
[ Enhance ] Status Report Endpoint to Support Additional Params and Return Neccessary Details 

### LINKED ISSUE #756: [ Enhance ] Status Report Endpoint to Support Additional Params and Return Neccessary Details
# Description 

## Create Status Report Endpoint
- [x] support connection to pages and monitor..
- [x] support message and date

Api Update
 

## Update Status Report Endpoint

- [x] support updation of connection to pages and monitor
- [x] support title of report to update.

Update

This will also lead us to update response of endpoints for Status Report,   `Get Status Report`, `Get all`, Including `Create Status Report`, `Create Status Report Update`. 

Endpoint

One of the Requirement: 
- In Update Status Report (Raycast feat), we need to have default values to selected report which user is looking to update.

- [x] Working on it

### PR DESCRIPTION
**Pull request by Nabhag8848**
## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [x] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation

## Description
- Closes #756 

### Before this PR

{Please add a screenshot here}

### After this PR

{Please add a screenshot here}

### CODE REVIEW

**Comment by thibaultleouay** [comment]
@Nabhag8848  would love if you could fix the tests please

**Comment by Nabhag8848** [comment]
will fix it before tommorow. 🙏🏻

**Comment by Nabhag8848** [comment]
@thibaultleouay done.

**Comment by mxkaske** [comment]
Hey @Nabhag8848, thanks for your work! Going to merge it within #848 and pushing it very soon. Improving our API errors as well.

Sorry it took so long.

**Pull request merged**
