### PR TITLE
Author avatar and link

### PR DESCRIPTION
**Pull request by AmoabaKelvin**
Add the user avatar and link to url to blog page

### CODE REVIEW

**Comment by thibaultleouay** [comment]
@AmoabaKelvin Thanks to you we have prettier in our github action and it's failling could you run 
``` pnpm format ```

**Comment by AmoabaKelvin** [comment]
Sure. I'm doing that ASAP

**Comment by AmoabaKelvin** [comment]
@thibaultleouay it has passed!

**Comment by mxkaske** [comment]
Lgtm! 🚀 Closes #196.

**Pull request merged**
