### PR TITLE
[ Enhance ] Status Report Endpoints 

### LINKED ISSUE #709: [ Enhance ] Get All Reports Endpoint on Server Side
### Reproduction / Replay Link (Optional)

- As Discussed in discord.

## Description

Once Status Report is Updated through endpoint, While getting that Status Report again, we are getting the Information Which is Old, we are getting a list of Ids from which i can get updated record when making the request again for that id. 

For Eg: 

When Record was created (init Version):
```
{
    "title": "Test Status Report",
    "status": "investigating",
    "id": 1,
    "status_report_updates": []
}
```

When Record is Updated through endpoint (say status is changed to monitoring), still we are getting investigating in current status field and inorder to get the updated version of this report we need to make another request by getting the last id within the status_report_updates array so in total 2 :

2nd request endpoint: http://localhost:3002/api-reference/status_report_update/get-status_report_update:id

```
{
    "title": "Test Status Report",.
    "status": "investigating", <- This should be Monitoring Status as we updated, 
    // we are getting first version status (not the updated status), true for above title prop too.
    "id": 1,
    "status_report_updates": [ 1 ] <- the id of updated version report
}
```

## Steps to reproduce:

1. Update the Status Report with Api
2. Get All Status Report with Api

## Expected behavior:

- Design reconsideration

Now when a user is created we should also create an record inside `status_report_update` table for every first creation that id will be 0 and that is the first version of report when created.

For Eg: when created for first time 

```
{
    "title": "Test Status Report",
    "status": "investigating",
    "id": 1,
    "status_report_updates": [0]
    // the id of report version  which is in different db 
    //having foreign key to status report table, length 1 signifies there has been zero time this reports have been updated 
   // and `0` is  an id of first version of the report.
}
```

When Updated, Title and Status Change for example:
```
{
    "title": "Test Status Report Updated version",.
    "status": "monitoring", <- Current updated Status, currently at this status
    "id": 1,
    "status_report_updates": [ 0 , 1 ] <- the id of updated version report added to array 
    // id: 1 signifies the id of first updated reported
    //  in this case its the current status report one.
}
```

## Comments
- [x] Currently Working On It

### Environment

_No response_

### PR DESCRIPTION
**Pull request by Nabhag8848**
## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [x] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation

## Description
- Closes #709 

### Before this PR

{Please add a screenshot here}

### After this PR

{Please add a screenshot here}

### CODE REVIEW

**Comment by Nabhag8848** [comment]
@mxkaske @thibaultleouay ready to review

**Comment by thibaultleouay** [comment]
@Nabhag8848 can you add a test for it please ?

**Comment by Nabhag8848** [comment]
> @Nabhag8848 can you add a test for it please ?

@thibaultleouay added, there was also a need for new data for seeding database. Thanks 🙏🏻!

**Review by thibaultleouay — CHANGES_REQUESTED** [review]
🔥 LGTM Thanks

**Pull request merged**
