### PR TITLE
fix Styling issue with copy to clipboard button on single code lines #947

### LINKED ISSUE #947: Styling issue with copy to clipboard button on single code lines [CSS]
### Reproduction / Replay Link (Optional)

_No response_

### Description

The copy button looks fine when the code block has multiple lines. If single line, it looks off.

Possible solution, reduce the `top-` value to fit within a single line.

Very first changelog on `/changelog` page:
CleanShot 2024-07-21 at 18 40 12@2x

Section on `/features/monitoring` page:
CleanShot 2024-07-21 at 18 42 11@2x

### Environment

_No response_

### PR DESCRIPTION
**Pull request by Ratnadeep2k**
…[CSS] #947

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation

## Description

fix Styling issue with copy to clipboard button on single code lines

### Before this PR

{Please add a screenshot here}

### After this PR
After

### CODE REVIEW

**Comment by mxkaske** [comment]
Hey @Ratnadeep2k! Thanks man, works totally fine. Just one little detail to match the style. Can we make the `right-2` to match the top position? Will make it a bit more cohesive (especially for multi-line text).

**Comment by Ratnadeep2k** [comment]
> Hey @Ratnadeep2k! Thanks man, works totally fine. Just one little detail to match the style. Can we make the `right-2` to match the top position? Will make it a bit more cohesive (especially for multi-line text).

 make right-2 .Please lookinto it

**Comment by mxkaske** [comment]
Thanks! 🙏

**Comment by Ratnadeep2k** [comment]
> Thanks! 🙏

Looking forward to contributing to this repo :)

**Comment by Ratnadeep2k** [comment]
> Thanks! 🙏

Please tell me why this branch not get merge ! 
ANy problem sir !

**Pull request merged**
